# Generated by Django 5.2.4 on 2025-07-16 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Empresa')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site da Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Vaga')),
                ('descricao', models.TextField(verbose_name='Descrição da Vaga')),
                ('nivel', models.CharField(choices=[('estagio', 'Estágio'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista')], max_length=20, verbose_name='Nível')),
                ('localidade', models.CharField(max_length=100, verbose_name='Localidade')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Vaga Ativa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app.empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
